### ISSUE TITLE
CLT and IAT should be pulled up not down

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#43]

**Comment by rusefillc** [comment]
@mck1117 @kon please mod the board you have

![image](https://user-images.githubusercontent.com/48498823/121306460-dbb6b580-c8cc-11eb-93d1-c0b52f26bf38.png)

**Comment by mck1117** [comment]
done

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/121416276-49b4b880-c971-11eb-8a76-a5fff710bb41.png)

**Comment by rusefillc** [comment]
@andreika-git can you please validate? is there an MCU module pull-up we are supposed to populate or do we just use external resistor?

**Comment by andreika-git** [comment]
Ok, here's the full story behind CLT/IAT pullups:

1) We do have the built-in configurable pullup/pulldown resistors for CLT/IAT in the input module. But their value is 4.7k (because it's an average "common good" value for 4 different inputs)

2) Most of the sensors work with 4.7k pullups (or pulldowns) just fine, but some users may still consider this as a limitation of the input module and may want to use their different "better" board-specific values.

3) This also covers the case when the same board may use both pull-up and pull-down for an analog input - depending on specific board configuration.

4) Hellen121vag is an open-source demo board, so I intentionally put those external resistors just to demostrate this possibility, and used "rusefi-legacy" 2.7k values. Especially since so many different VAG configurations exist for the one single board.

5) The only thing left to do was to run through all VAG diagrams and check whether pull-ups or pull-downs are needed for some of them. That was supposed to be a separate task in the TODO list... And that's where the issue came from... :)

6) As for now, I still don't know if these pullups are valid for all VAG configurations. Is we _assume_ they are, then we can just leave the current (fixed) version as is.

**Comment by mck1117** [comment]
Another factor is that the resistor arrays are pretty inaccurate, and the pullup accuracy really only matters for temperature sensors.
